// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string):Promise<main.State>;

export function CurrentState():Promise<main.State>;

export function LoadState():Promise<main.State>;

export function OpenTerminal(arg1:string):Promise<void>;

export function PickAndAddProject():Promise<main.State>;

export function PositionMonitorWindow():Promise<void>;

export function RefreshState():Promise<main.State>;

export function RemoveProject(arg1:string):Promise<main.State>;

export function RenameWorktree(arg1:string,arg2:string):Promise<main.State>;

export function SetActivity(arg1:string,arg2:string,arg3:string):Promise<main.State>;

export function SetAlwaysOnTop(arg1:boolean):Promise<main.State>;

export function Snapshot():Promise<main.State>;
