// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function CurrentState() {
  return window['go']['main']['App']['CurrentState']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PickAndAddProject() {
  return window['go']['main']['App']['PickAndAddProject']();
}

export function PositionMonitorWindow() {
  return window['go']['main']['App']['PositionMonitorWindow']();
}

export function RefreshState() {
  return window['go']['main']['App']['RefreshState']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RenameWorktree(arg1, arg2) {
  return window['go']['main']['App']['RenameWorktree'](arg1, arg2);
}

export function SetActivity(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetActivity'](arg1, arg2, arg3);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}
